version: "3.9"

x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: "1"
  # App
  APP_NAME: "go-clean-template"
  APP_VERSION: "1.0.0"
  # HTTP settings
  HTTP_PORT: "8080"
  HTTP_USE_PREFORK_MODE: "false"
  # Logger
  LOG_LEVEL: "debug"
  # PG
  PG_POOL_MAX: "2"
  PG_URL: "postgres://postgres:password@db:5432/postgres"
  # Metrics
  METRICS_ENABLED: "true"
  # Swagger
  SWAGGER_ENABLED: "true"

x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "postgres" 

services:
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_network:
        aliases:
          - db.lvh.me
  caddy:
    image: caddy:alpine
    depends_on:
      - frontend
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'caddy-data:/data/caddy'
      - ./apps/caddy/Caddyfile.prod:/etc/caddy/Caddyfile
    environment:
      DOMAIN: "${DOMAIN}"
      EMAIL: "${EMAIL}"
      LOG_FILE: "${LOG_FILE}"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
    restart: always

  frontend:
    build: 
      context: ./apps/frontend
    expose:
      - '3333'
    volumes:
      - ./frontend:/web
    restart: always
  
  
  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      app_network:
        aliases:
          - app.lvh.me
    restart: unless-stopped

  # redis:
  #   image: redis:alpine
  #   expose:
  #     - '6379'
  #   logging:
  #     driver: none
  #   restart: no

volumes:
  db_data:
  caddy-data:
    driver: local

networks:
  app_network:
    external: false